<a href="https://colab.research.google.com/github/swatigohite/Data-Science/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy
arr = numpy.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
print(np.__version__)

1.25.2


In [ ]:
import numpy as np
arr = np.array((1,2,3,4))
print(arr)

[1 2 3 4]


**1** **Dimension**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


**2** **Dimension**

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


**3** **Dimension**

In [ ]:
import numpy as np
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


**Access** **Array** **Element**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[1])
print(arr[2])
print(arr[1] + arr[2])

2
3
5


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print('2nd element of 1st row', arr[0,1])

2nd element of 1st row 2


In [ ]:
import numpy as np
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr[1,1,2])
print(arr[0,0,2])
print(arr[1,0,0])

15
3
9


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print('last element of 2nd dim',arr[1,-1])
print('last element of 1st dim',arr[0,-1])

last element of 2nd dim 8
last element of 1st dim 4


**Slicing**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:4])
print(arr[0:5])
print(arr[1:])
print(arr[:4])

[2 3 4]
[1 2 3 4 5]
[2 3 4 5 6 7 8]
[1 2 3 4]


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1, 1:3])
print(arr[0, :3])
print(arr[1, 0:])
print(arr[0: , 1:3])
print(arr[:2, 1:3])

[6 7]
[1 2 3]
[5 6 7 8]
[[2 3]
 [6 7]]
[[2 3]
 [6 7]]


**Exercise (numpy)**

In [ ]:
import numpy as np
print(np.__version__)

1.25.2


In [ ]:
import numpy as np
x = np.array([1,0,0,0])
# print("original array: ")
print(x)
print("array is non-zero: ")
print(np.any(x))

x = np.array([0,0,0,0])
# print("original array: ")
print(x)
print("array is non-zero: ")
print(np.any(x))

[1 0 0 0]
array is non-zero: 
True
[0 0 0 0]
array is non-zero: 
False


In [ ]:
import numpy as np
x = np.array([23,56,45,89,87])
y = np.array([23,67,45,89,56])
print(x)
print(y)

print("equal")
print(np.equal(x,y))
print("greater")
print(np.greater(x,y))
print("less")
print(np.less(x,y))
print("greater_equal")
print(np.greater_equal(x,y))
print("less_equal")
print(np.less_equal(x,y))

[23 56 45 89 87]
[23 67 45 89 56]
equal
[ True False  True  True False]
greater
[False False False False  True]
less
[False  True False False False]
greater_equal
[ True False  True  True  True]
less_equal
[ True  True  True  True False]


In [ ]:
import numpy as np
x = np.array([1,7,13,105])
print(x)
print("size of the memory occupied by the array: ")
print("%d bytes " % (x.size * x.itemsize))

[  1   7  13 105]
size of the memory occupied by the array: 
32 bytes 


In [ ]:
import numpy as np
array = np.arange(30, 71)
print("the array of the integer is : ")
print(array)

the array of the integer is : 
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
import numpy as np
array = np.arange(30, 71, 2)
print("the array of the even integer is : ")
print(array)

the array of the integer is : 
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [ ]:
import numpy as np
array = np.arange(30, 71, 3)
print("the array of the even integer is : ")
print(array)

the array of the even integer is : 
[30 33 36 39 42 45 48 51 54 57 60 63 66 69]


In [ ]:
import numpy as np
array = np.identity(3)
print("3x3 matrix: ")
print(array)

3x3 matrix: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
